### ISSUE TITLE
Invalid Argument

### ISSUE THREAD

**Issue by sallyYYS** [yfsong0709/RA-GCNv1#2]
你好，我运行的时候总是出现参数问题，请问你知道是什么原因吗？谢谢~
下面是运行结果：

************************************************
The running config is presented as follows:
path: /datasets/NTU_RGBD
config_id: 3301
resume: False
evaluate: True
extract: False
visualization: False
gpus: [0, 1]
seed: 1
visualize_sample: 0
visualize_class: 0
visualize_stream: 0
visualize_frames: []
subset: cs
max_frame: 300
batch_size: 16
data_transform: True
occlusion_part: [1]
occlusion_time: 0
pretrained: True
model_stream: 3
gcn_kernel_size: [5, 2]
drop_prob: 0.5
max_epoch: 50
learning_rate: 0.1
adjust_lr: [10, 30]
************************************************

Starting preparing ...
GPU0 used: 571.27734375M
Traceback (most recent call last):
  File "main.py", line 109, in <module>
    main()
  File "main.py", line 53, in main
    p = Processor(args)
  File "D:\Dingaling\DeepLearning\RA-GCNv1-master\src\processor.py", line 28, in __init__
    self.device = U.check_gpu(args.gpus)
  File "D:\Dingaling\DeepLearning\RA-GCNv1-master\src\utils.py", line 11, in check_gpu
    handle = pynvml.nvmlDeviceGetHandleByIndex(i)
  File "D:\Anaconda3\envs\pytorch36\lib\site-packages\pynvml.py", line 807, in nvmlDeviceGetHandleByIndex
    _nvmlCheckReturn(ret)
  File "D:\Anaconda3\envs\pytorch36\lib\site-packages\pynvml.py", line 310, in _nvmlCheckReturn
    raise NVMLError(ret)
pynvml.NVMLError_InvalidArgument: Invalid Argument

**Comment by yfsong0709** [comment]
根据反馈的结果来看，感觉应该是你的电脑只有GPU0，找不到GPU1。你是不是只有一块GPU？那样的话需要把gpus参数改成[0]再试一试。
